# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test: 
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:13
        environment:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/invictus
          POSTGRES_DB: invictus
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432

    steps:
      - checkout
          
      - run:
          name: Setup Project Environment
          command: |
            sudo apt-get update
            sudo apt-get -y install postgresql-client
            whoami
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"

      - run:
          name: Run Test
          command: |
             virtualenv venv
              . venv/bin/activate
             pip install --upgrade pip 
             pip install -r requirements.txt
             python manage.py makemigrations
             python manage.py migrate
             python manage.py test

workflows:
  sample: 
    jobs:
      - build-and-test
